### PR TITLE
Insertion Sort by Megha Gupta

### PR DESCRIPTION
**Pull request by Megha1209**

### CODE REVIEW

**Comment by Shreyans13** [comment]
Hello Megha
Add your name in contribution file

**Comment by Megha1209** [comment]
Megha Gupta

**Comment by Megha1209** [comment]
Can you help me do that please how to do it?

**Comment by Shreyans13** [comment]
You need not change that. What I was asking is that there us contributors file in the repository
https://github.com/Megha1209/Hacktoberfest-2019/blob/master/CONTRIBUTING.md
Add your name and github profile link here. So your name appears on the contribution list. Please ask if you need any help.

**Comment by Shreyans13** [comment]
If you have any problem just ask.

**Pull request merged**
