### PR TITLE
added Exponential_Search

### PR DESCRIPTION
**Pull request by aryantanny**
Exponential_Search when array entered is in sorted order

### CODE REVIEW

**Comment by Shreyans13** [comment]
Update contribution file

**Comment by aryantanny** [comment]
already updated that. it is saying to resolve conflicts, although i am not able to understand what the conflicts are

**Comment by Shreyans13** [comment]
your contributors.md file and my file were little different. No worries!!!!
I resolved it.

**Comment by aryantanny** [comment]
okay. thanks man!!

**Pull request merged**
